services:
  librarymanager.api:
    image: ${DOCKER_REGISTRY-}librarymanagerapi
    build:
      context: .
      dockerfile: LibraryManager.API/Dockerfile
    depends_on:
      - librarydatabase
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:81
      - ConnectionStrings__MSSQLWrite=Server=sqlserver;Initial Catalog=LibraryDb;User ID=sa;Password=P@ssw0rd123!;Trusted_Connection=False; TrustServerCertificate=True;
    ports:
      - "8080:80"
      - "8081:81"

  librarydatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd123!    
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:     